name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: npx turbo build
        env:
          NODE_ENV: production
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webamp-build
          path: |
            packages/webamp/built
            packages/webamp/dist
